# appveyor.yml
---
environment:
  matrix:
  - TOXENV: py35
  - TOXENV: py36
  - TOXENV: py37

build: off

install:
- python -m pip install --upgrade pip
- pip install tox tox-conda

test_script:
- tox

