name: taurenmd
channels:
    - conda-forge
    - omnia
    - defaults
dependencies:
    - pip
    - python=3.7
    - mdanalysis
    - mdtraj
    - openmm
    - pip:
        - bioplottemplates
        - pyquaternion
